### ISSUE TITLE
Export feature

### ISSUE THREAD

**Issue by scrouthtv** [scrouthtv/gosc#1]
https://github.com/nsf/termbox-go/issues/239
@pedroalbanese

**Comment by scrouthtv** [comment]
Considering this spreadsheet:

![image](https://user-images.githubusercontent.com/23227405/125312441-8c80fc00-e334-11eb-87f7-214077010e44.png)

Where
 - A0, B0, C0 are left justified, centered, right justified labels
 - A1, B1 are numeric constants
 - C1 is a basic formula (A1 + B1)

C `sc` generates an output like this:
```scala
# This data file was generated by the Spreadsheet Calculator.
# You almost certainly shouldn't edit it.

leftstring A0 = "asdf"
label B0 = "qwerty"
rightstring C0 = "foobar"
let A1 = 25
let B1 = 33
let C1 = A1+B1
goto C1 A0
```

Or plaintext:
```
asdf        qwerty      foobar
     25.00     33.00     58.00

                                        
                              
```

**Comment by scrouthtv** [comment]
For C `sc`, all cells in the export are fixed-width of ten characters - even if the text is longer than 10 characters.

How do you expect this feature to work? Should I simply crop everything after 10 characters or search for the cell with the longest text?

**Comment by pedroalbanese** [comment]
The P command saves as .sc (structured)
The W command saves file as .asc (plain text):
<pre>
  Weight    Silver    Electricity     GAS       Days   
      54.0      6.30         160.00    100.00         3

Material      340.20          Piece    540.00
Labor         199.80       Subtotal    558.50

Guarantee      55.85
Total         614.35
</pre>

The W command appears to adjust cell lengths in plain text. GOSC allows to view and edit sc files, but have no export scheme as W command.

**Comment by pedroalbanese** [comment]
The sc (both in C and Go) have a command to set the column length. I believe it is not based on the length of the longest word, but rather on the column attributes (f command).

**Comment by scrouthtv** [comment]
You could try tag v1.1 -- it's working now. Press W to enter a filename, then export somewhere. Attention: it will silently overwrite any existing files

**Comment by pedroalbanese** [comment]
First thank you. It's working, but there's a bug when there's an empty row:

"error exporting: cell at address A2 does not exist in spreadsheet"

**Comment by scrouthtv** [comment]
Should be fixed now

**Comment by pedroalbanese** [comment]
There is just a little detail missing:

```
# github.com/scrouthtv/gosc/internal/sheet
internal\sheet\export.go:28:8: undefined: errors.Is
```

Thanks!

**Comment by scrouthtv** [comment]
Weird. Is this the output you get when executing `go run .`?

Because it certainly works for me:
![Peek 2021-07-17 18-37](https://user-images.githubusercontent.com/23227405/126043746-f5d26d42-d86d-42f9-ba8b-45871eecfb5b.gif)

**Comment by pedroalbanese** [comment]
No, it's when try to compile. ```go run .``` also results this

**Comment by scrouthtv** [comment]
What do you mean by compile? `go build .`?

**Comment by pedroalbanese** [comment]
Yes. The problem was the version, I'm using Go 1.12 (last one that still runs on XP). Now I've compiled it with version 1.15.3, but the problem with the non-existent cell persists.

I'm using this example:

<pre>
# This data file was generated by Spreadsheet Calculator.
# You almost certainly shouldn't edit it.

format E 10 0 0
format F 10 2 0
format G 10 2 0
format A 10 1 0
format B 10 2 0
format C 10 2 0
format D 10 2 0
leftstring A3 = "Material"
let B3 = A1*B1
let B6 = (A1*B1+(A1*10-A1*B1)+C1/30*E1+D1/40)/100*10
label C0 = "Light"
label D0 = "GAS"
label E0 = "Days"
let A1 = 54
let C1 = 160
leftstring A7 = "Total"
label B0 = "Silver"
rightstring C3 = "Piece"
let D3 = B3+B4
rightstring C4 = "Subtotal"
let B7 = D4+B6
label A0 = "Weight"
let D1 = 100
let E1 = 3
let D4 = A1*B1+(A1*10-A1*B1)+C1/30*E1+D1/40
leftstring A6 = "Guarantee"
let B1 = 6.3
leftstring A4 = "Labor"
let B4 = A1*10-B3
goto D4 A0
</pre>

**Comment by scrouthtv** [comment]
1) Technically, you can compile it using a newer Go version ([anything from 1.13 upwards](https://pkg.go.dev/errors#Is)) and still run the final executable under XP.

2) I think it should finally be fixed :') -- I get this output with your example (the light dashes are spaces):
![image](https://user-images.githubusercontent.com/23227405/126050792-b1eb0302-58ff-4eef-871d-526dcd461a02.png)

Sorry for the late answer...

**Comment by pedroalbanese** [comment]
Great!

Wow, I managed to build with version 1.12.1 !! 

Great job! I do not know how to thank you.. Thank You very much!

**Comment by scrouthtv** [comment]
No worries man.. this was actually fun :)

I think I might revisit this later and add some more features

**Comment by pedroalbanese** [comment]
Greetings! 

Man, I need your help, can you email me pedroalbanese@hotmail.com? I think you will like it 

Thanks!
